# Generated by Django 3.0.8 on 2020-09-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок мероприятия')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='описание мероприятия')),
                ('date', models.DateField(verbose_name='дата начала')),
                ('time_start', models.TimeField(verbose_name='время начала')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
        ),
    ]
