# Generated by Django 3.0.8 on 2020-10-01 09:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=10, validators=[main.models.validate_date]),
        ),
    ]
