# Generated by Django 3.0.8 on 2020-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201001_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_start',
        ),
        migrations.AddField(
            model_name='event',
            name='hour_start',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='minute_start',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
